# Generated by Django 3.2.8 on 2021-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('estilo', models.CharField(max_length=25)),
                ('fecha_formacion', models.DateField()),
                ('residencia', models.CharField(max_length=25)),
                ('integrantes', models.TextField(blank=True)),
                ('historia', models.TextField(blank=True)),
                ('discos', models.TextField(blank=True)),
                ('fotos', models.ImageField(blank=True, upload_to='')),
                ('tema_presentacion', models.Field(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('youtube', models.URLField(blank=True)),
                ('spotify', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('otro', models.URLField(blank=True)),
            ],
        ),
    ]
