# Generated by Django 3.2.8 on 2021-10-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='tema_presentacion',
        ),
    ]
