# Generated by Django 3.2.8 on 2021-10-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_banda_tema_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='tema_presentacion',
            field=models.URLField(blank=True),
        ),
    ]
