# Generated by Django 3.2.8 on 2021-10-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_banda_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='bandas/fotos'),
        ),
    ]
