# Generated by Django 3.2.8 on 2021-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_banda_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='presentacion',
            field=models.TextField(blank=True),
        ),
    ]
