# Generated by Django 3.2.8 on 2021-11-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_banda_presentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='fotos',
            new_name='foto',
        ),
    ]
