# Generated by Django 3.2.8 on 2021-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_fotos_banda_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=25)),
                ('noticia', models.TextField()),
                ('foto', models.ImageField(upload_to='noticia/fotos')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
