# Generated by Django 3.2.8 on 2021-11-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banda',
            options={'verbose_name_plural': 'Bandas'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name_plural': 'Noticias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='fecha_evento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('NOTICIA', 'Noticia'), ('EVENTO', 'Evento')], default='NOTICIA', max_length=8),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto',
            field=models.ImageField(upload_to='noticias/fotos'),
        ),
    ]
