# Generated by Django 3.2.8 on 2021-11-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20211117_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('banda', models.CharField(max_length=25)),
                ('fecha_evento', models.DateField()),
                ('horario', models.DateTimeField()),
                ('direccion', models.CharField(max_length=50)),
                ('cometario', models.TextField(blank=True)),
                ('link_entrada', models.URLField(blank=True)),
                ('link_banda', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tipo',
        ),
    ]
