# Generated by Django 3.2.8 on 2021-11-18 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20211118_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='cometario',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(),
        ),
    ]
