# Generated by Django 3.2.8 on 2021-11-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_noticia_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='fecha',
            new_name='fecha_alta',
        ),
    ]
